### PR TITLE
Rework.

### PR DESCRIPTION
**Pull request by ypid**

### CODE REVIEW

**Comment by drybjed** [comment]
Awesome work, thank you! :-)

**Comment by drybjed** [comment]
Ah, looks like `debops.libvirtd` role needs to be updated first, I'll check it out.

**Comment by drybjed** [comment]
@ypid OK, the variable issue in `debops.libvirtd` is fixed, but the role would need to be tagged for Ansible Galaxy. Do you have similar rework for it as well?

**Comment by ypid** [comment]
@drybjed I just did: https://github.com/debops/ansible-libvirtd/pull/6 :)

**Pull request merged**
